@startuml
left to right direction
actor User as "User"

rectangle "Function" {
    usecase UC1a as "display the sorted
    country population"

    usecase UC2a as "display the sorted
    country population by continent"

    usecase UC3a as "display the sorted
    country population by region"

    usecase UC4a as "display the top 5
    country population"

    usecase UC5a as "display the top 5
    country population by continent"

    usecase UC6a as "display the top 5
    country population by region"

    usecase UC7a as "display the sorted
    city population"

    usecase UC8a as "display the sorted
    city population by continent"

    User --> UC1a
    User --> UC2a
    User --> UC3a
    User --> UC4a
    User --> UC5a
    User --> UC6a
    User --> UC7a
    User --> UC8a
}
@enduml